In [1]:
import pandas as pd 

print("")

In [2]:
#Spreadsheets Data
df = pd.DataFrame({
    "Name": ["Rahul", "Priya"],
    "Marks": [85, 92]
})

df


#Time-Frame Data
print("-----_------_")
import pandas as pd

data = {
    "Date": ["2026-01-01", "2026-01-02", "2026-01-03"],
    "Sales": [1000, 1200, 900]
}

df = pd.DataFrame(data)
df

-----_------_

         Date  Sales
0  2026-01-01   1000
1  2026-01-02   1200
2  2026-01-03    900

<b><mark>#Series vs Data Frame 



<strong>Series:

A Series is a one-dimensional labeled array that can hold any data type: integers, floats, strings, or even Python
objects. Each element in the Series has a unique label called an index.


· It is often used to track changes or patterns over time, such as daily temperatures, stock prices, or sales revenue.




<strong> DataFrame


· A DataFrame is a two-dimensional labeled data structure in Pandas, similar to a table in a database, an Excel
spreadsheet, or a SQL table.

It consists of rows and columns, where:

Rows have indices (labels).
Columns have names (labels).

In [3]:
import pandas as pd

marks = pd.Series([85, 92, 78, 90])

print(marks)

import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Aman"],
    "Age": [18, 19, 17],
    "Marks": [85, 92, 78]
}

df = pd.DataFrame(data)

print(df)

0    85
1    92
2    78
3    90
dtype: int64
    Name  Age  Marks
0  Rahul   18     85
1  Priya   19     92
2   Aman   17     78

<b> Read Data From  A CSV File into a Data Frame

In [4]:
df = pd.read_csv(r"C:\Users\shobh\OneDrive\Attachments\Documents\Desktop\py\student_placement_salary_elite_v2.csv",encoding = "utf-8")


df

,student_id,cgpa,branch,college_tier,python_skill,dsa_skill,ml_skill,web_dev_skill,coding_score,communication_score,aptitude_score,internships,projects,backlogs,resume_score,skill_score,placed,company_type,job_role,salary_lpa
0,S0,6.87,Civil,1,1,1,0,0,15.6,4.3,92.0,1,3,0,62.6,2,1,MNC,Software Engineer,63.55
1,S1,6.52,Civil,2,1,0,0,1,13.9,5.8,62.0,1,6,0,77.5,2,1,MNC,Data Scientist,75.17
2,S2,5.33,IT,1,1,1,1,0,9.8,8.1,66.4,0,5,1,76.0,3,1,MNC,Software Engineer,80.44
3,S3,6.04,Civil,3,1,0,1,0,39.5,9.6,83.6,0,6,0,74.3,2,1,MNC,Software Engineer,72.11
4,S4,6.78,Mechanical,2,0,1,0,1,7.5,9.9,86.3,0,3,0,66.8,2,1,Mid-size,Software Engineer,67.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,S8995,6.51,IT,2,1,0,0,1,56.6,8.2,43.2,0,2,0,50.1,2,1,MNC,Analyst,75.29
8996,S8996,7.74,IT,3,1,1,1,0,67.9,6.3,49.4,0,2,0,57.6,3,1,MNC,Analyst,69.30
8997,S8997,7.14,CSE,3,1,0,1,1,40.4,8.0,67.4,1,1,0,65.8,3,1,MNC,Data Scientist,85.58
8998,S8998,5.21,IT,1,1,0,0,1,79.9,6.3,77.2,1,6,0,78.9,2,1,Mid-size,Software Engineer,54.54
8999,S8999,6.05,Civil,2,1,1,0,0,80.0,6.0,79.1,0,2,0,49.2,2,1,MNC,Software Engineer,84.32

<b> Read Data From  A .xlsx File into a Data Frame

In [5]:
df = pd.read_excel(r"C:\Users\shobh\Downloads\indian_student_dataset.xlsx")

print(df)

    Student_ID           Name  Age       City            Course  Marks  \
0            1    Priya Verma   18    Kolkata      Data Science     93
1            2   Vikram Yadav   19       Pune   Web Development     63
2            3    Rohan Mehta   19    Kolkata                AI     74
3            4   Rahul Sharma   22    Lucknow    Cyber Security     97
4            5   Vikram Yadav   24    Kolkata                AI     96
5            6   Vikram Yadav   21  Bangalore    Cyber Security     76
6            7  Anjali Kapoor   20    Kolkata  Machine Learning     74
7            8    Priya Verma   20       Pune            Python     87
8            9     Kavya Nair   25  Hyderabad  Machine Learning     70
9           10    Priya Verma   19  Bangalore  Machine Learning     85
10          11    Rohan Mehta   20    Kolkata   Web Development     93
11          12     Kavya Nair   22    Lucknow  Machine Learning     89
12          13   Vikram Yadav   18       Pune  Machine Learning     71
13          14  Anjali Kapoor   21      Delhi    Cyber Security     68
14          15     Kavya Nair   22    Chennai    Cyber Security     76
15          16     Aman Singh   21    Kolkata    Cyber Security     72
16          17     Neha Gupta   20       Pune                AI     79
17          18     Kavya Nair   23  Bangalore    Cyber Security     74
18          19    Arjun Patel   21    Kolkata   Web Development     63
19          20  Anjali Kapoor   20  Hyderabad   Web Development    100
20          21  Anjali Kapoor   23      Delhi                AI     69
21          22     Aman Singh   25       Pune    Cyber Security     95
22          23     Kavya Nair   25      Delhi   Web Development     74
23          24     Neha Gupta   19     Mumbai  Machine Learning     65
24          25     Sneha Iyer   18    Lucknow  Machine Learning     64
25          26     Sneha Iyer   24    Kolkata  Machine Learning     81
26          27  Anjali Kapoor   20     Mumbai      Data Science     77
27          28  Anjali Kapoor   24      Delhi  Machine Learning     92
28          29     Aman Singh   22     Mumbai   Web Development     91
29          30     Neha Gupta   18      Delhi      Data Science     84
30          31  Anjali Kapoor   20  Bangalore  Machine Learning     81
31          32   Rahul Sharma   21      Delhi   Web Development     64
32          33    Arjun Patel   21     Mumbai  Machine Learning     92
33          34  Anjali Kapoor   25     Mumbai   Web Development    100
34          35    Priya Verma   25  Hyderabad      Data Science     59
35          36     Sneha Iyer   25  Hyderabad   Web Development     73
36          37    Rohan Mehta   18  Bangalore            Python     70
37          38  Anjali Kapoor   20  Bangalore      Data Science     96
38          39     Aman Singh   20      Delhi      Data Science     67
39          40     Aman Singh   22  Bangalore      Data Science     68
40          41    Arjun Patel   25  Bangalore  Machine Learning     88
41          42    Arjun Patel   23    Lucknow                AI     90
42          43    Priya Verma   23    Lucknow  Machine Learning     87
43          44     Neha Gupta   23    Kolkata   Web Development     77
44          45     Kavya Nair   25       Pune                AI     61
45          46     Sneha Iyer   18  Bangalore    Cyber Security     92
46          47  Anjali Kapoor   24      Delhi   Web Development     85
47          48   Rahul Sharma   19  Bangalore            Python     78
48          49  Anjali Kapoor   21     Mumbai                AI     67
49          50    Arjun Patel   18    Chennai      Data Science     63

    Attendance_Percent Placement  Monthly_Stipend   Join_Date
0                   71       Yes            48229  2026-06-12
1                   96        No            11901  2026-10-03
2                   67        No            24636  2026-12-23
3                   75       Yes            47867  2026-10-20
4                   80       Yes            45434  2026-04-09
5                   96       Yes            30610  2026-07-25
6                   66       Yes            49209  2026-02-10
7                   63       Yes            39037  2026-03-05
8                   76        No            23559  2026-03-07
9                   98       Yes            38824  2026-05-28
10                  73        No            43834  2026-03-28
11                  73       Yes            36524  2026-03-23
12                  89       Yes            35746  2026-12-01
13                  93        No            45835  2026-06-19
14                  77       Yes            13516  2026-04-28
15                  85        No            30130  2026-08-11
16                  88       Yes            35358  2026-11-12
17                  68        No            43416  2026-10-28
18                  99        No            34318  2026-07-10
19                  91       Yes            40936  2026-03-19
20                  95       Yes            19400  2026-05-10
21                  78       Yes            22399  2026-06-22
22                  62       Yes            46474  2026-06-08
23                  73        No            15003  2026-02-28
24                  66        No            16323  2026-08-19
25                  79       Yes            44863  2026-11-04
26                  61        No            36027  2026-07-26
27                  81        No            41505  2026-11-17
28                  85       Yes            30023  2026-04-22
29                  63       Yes            19960  2026-03-06
30                  69        No            17050  2026-09-22
31                  98        No            24091  2026-11-11
32                  61        No            25106  2026-11-12
33                  99       Yes            13386  2026-11-08
34                  73        No            11856  2026-11-14
35                  84        No            41270  2026-08-10
36                  63        No            27508  2026-04-04
37                 100        No            34770  2026-10-09
38                  83       Yes            25015  2026-01-16
39                  96        No            47052  2026-02-10
40                  77        No            27801  2026-07-08
41                  81       Yes            13549  2026-03-03
42                  92        No            26664  2026-01-31
43                  98        No            30558  2026-09-02
44                  85        No            47215  2026-04-05
45                  93        No            33015  2026-05-10
46                  87       Yes            35915  2026-09-09
47                  70       Yes            22859  2026-12-29
48                  79        No            35633  2026-08-31
49                  71        No            27862  2026-04-18

<b> Read Data From  A .json File into a Data Frame

In [6]:
df = pd.read_json(r"C:\Users\shobh\Downloads\sample_orders_data.json")

print(df)

    order_id customer_name     product  quantity  price       city  order_date
0          1    Aman Singh  Headphones         2  76814     Mumbai  2026-02-12
1          2    Sneha Iyer      Laptop         4  59312    Kolkata  2026-04-01
2          3   Arjun Patel     Printer         5   6301    Chennai  2026-05-25
3          4    Aman Singh  Headphones         4  29407    Kolkata  2026-05-02
4          5  Rahul Sharma    Keyboard         4   5225    Chennai  2026-04-11
5          6    Neha Gupta       Mouse         4  47202       Pune  2026-01-13
6          7    Sneha Iyer      Camera         3  27412  Hyderabad  2026-04-02
7          8  Rahul Sharma      Tablet         5  76140     Mumbai  2026-04-04
8          9   Priya Verma  Headphones         1  24044  Hyderabad  2026-04-15
9         10    Sneha Iyer  Headphones         2  23665    Lucknow  2026-06-16
10        11    Neha Gupta      Tablet         4  44366       Pune  2026-01-24
11        12   Priya Verma  Headphones         3   3191    Lucknow  2026-01-01
12        13    Sneha Iyer    Keyboard         1  16796      Delhi  2026-02-21
13        14   Arjun Patel      Tablet         3  62294      Delhi  2026-03-30
14        15    Neha Gupta    Keyboard         4  14536    Chennai  2026-04-18
15        16   Priya Verma       Mouse         5  68562  Bangalore  2026-04-16
16        17  Rahul Sharma  Headphones         5  70045  Hyderabad  2026-01-15
17        18   Arjun Patel     Monitor         2  24868  Bangalore  2026-05-05
18        19    Sneha Iyer     Printer         3  14678     Mumbai  2026-04-10
19        20    Aman Singh      Laptop         2  57062     Mumbai  2026-03-18

<b> Creating a dataframe and saving it to csv and .xlsx file

In [7]:
data = {
    "Year": [2021,2022,2023,2034],
    "Resturant": ["China Bowl","Subway","Dominoz","Burger Singh"],
    "Sales": [500000,21000,88884,34233],
    "Overall": ["Good","Good","Good","Bad"]
}

df = pd.DataFrame(data)

df.index = range(1,len(df)+1)

print(df)


df.to_csv("output.csv")



#To remove indices 

df.to_csv("output.csv",index=False)



#Saving to excel file


df.to_excel("output2.xlsx")


#To json use : df.to_json(filename.json)

   Year     Resturant   Sales Overall
1  2021    China Bowl  500000    Good
2  2022        Subway   21000    Good
3  2023       Dominoz   88884    Good
4  2034  Burger Singh   34233     Bad

<b> Data Exploration

In [8]:
#exploring first 5 or last 5 rows of data 

#head(n) and tail(n)


data =pd.read_csv(r"C:\Users\shobh\OneDrive\Attachments\Documents\Desktop\py\student_placement_salary_elite_v2.csv",encoding = "utf-8")

# # print(data.head(5))

print(data.shape)

# print(data.columns)

data.index = range(1,len(data)+1)
print(data.info())

(9000, 20)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 1 to 9000
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   student_id           9000 non-null   object
 1   cgpa                 9000 non-null   float64
 2   branch               9000 non-null   object
 3   college_tier         9000 non-null   int64
 4   python_skill         9000 non-null   int64
 5   dsa_skill            9000 non-null   int64
 6   ml_skill             9000 non-null   int64
 7   web_dev_skill        9000 non-null   int64
 8   coding_score         9000 non-null   float64
 9   communication_score  9000 non-null   float64
 10  aptitude_score       9000 non-null   float64
 11  internships          9000 non-null   int64
 12  projects             9000 non-null   int64
 13  backlogs             9000 non-null   int64
 14  resume_score         9000 non-null   float64
 15  skill_score          9000 non-null   int64
 16  placed               9000 non-null   int64
 17  company_type         7702 non-null   object
 18  job_role             7702 non-null   object
 19  salary_lpa           9000 non-null   float64
dtypes: float64(6), int64(10), object(4)
memory usage: 1.4+ MB
None

<b> Commonly used functions while data exploration 


data.head()

data.tail()

data.shape

data.columns

data.info()

<b>Describe methords in python

In [9]:
data = {
    "Year": [2021,2022,2023,2034],
    "Resturant": ["China Bowl","Subway","Dominoz","Burger Singh"],
    "Sales": [500000,21000,88884,34233],
    "Overall": ["Good","Good","Good","Bad"]
}

df = pd.DataFrame(data)

print("Descriptive Statictics :\n",df.describe())

Descriptive Statictics :
               Year         Sales
count     4.000000       4.00000
mean   2025.000000  161029.25000
std       6.055301  227882.70837
min    2021.000000   21000.00000
25%    2021.750000   30924.75000
50%    2022.500000   61558.50000
75%    2025.750000  191663.00000
max    2034.000000  500000.00000

<b> Data Manipulation

In [10]:
data = {
    "Year": [2021,2022,2023,2034],
    "Resturant": ["China Bowl","Subway","Dominoz","Burger Singh"],
    "Sales": [500000,21000,88884,34233],
    "Overall": ["Good","Good","Good","Bad"]
}

df = pd.DataFrame(data)

#Selecting single coloumn

# print(df["Sales"])

#Selecting multiple coloumn

print(df[["Overall","Sales"]])

  Overall   Sales
0    Good  500000
1    Good   21000
2    Good   88884
3     Bad   34233

<b> Filtering a Row

In [11]:
data = {
    "Year": [2021,2022,2023,2034],
    "Resturant": ["China Bowl","Subway","Dominoz","Burger Singh"],
    "Sales": [500000,21000,88884,34233],
    "Overall": ["Good","Good","Good","Bad"]
}

df = pd.DataFrame(data)

#Single Condition

# high_sales = df[df["Sales"]>50000]

# print(high_sales)


#Multiple Conditions 


overall = df[(df["Sales"]>30000) & (df["Overall"]=="Good")]

print(overall)


a = df[(df["Sales"]>5000) | (df["Overall"]=="Bad")]


print(a)

   Year   Resturant   Sales Overall
0  2021  China Bowl  500000    Good
2  2023     Dominoz   88884    Good
   Year     Resturant   Sales Overall
0  2021    China Bowl  500000    Good
1  2022        Subway   21000    Good
2  2023       Dominoz   88884    Good
3  2034  Burger Singh   34233     Bad

#Python Boonlean Operators 

Easy Memory Trick 🔥

Operation	Symbol

AND   &

OR	|

NOT	~

<mark><b><strong> Video 1 Ended

<b><i> Video 2 Started

<b> Modifying Data

In [12]:
#Coloumn add update and remove 

# adding coloumn directly

data = {
    "Year": [2021,2022,2023,2034],
    "Resturant": ["China Bowl","Subway","Dominoz","Burger Singh"],
    "Sales": [500000,21000,88884,34233],
    "Overall": ["Good","Good","Good","Bad"]
}


df = pd.DataFrame(data)

# df["Sales"] =  df["Sales"]+1


# df["Yearly Sales"] = df["Sales"]*12]

# #but it will add to the end of the dataframe 

# print(df)

#using insert() on a specific position 
print("\n----------X----------\n")
df.insert(1,"Resturant Id",[101,102,103,104])

print(df)

----------X----------

   Year  Resturant Id     Resturant   Sales Overall
0  2021           101    China Bowl  500000    Good
1  2022           102        Subway   21000    Good
2  2023           103       Dominoz   88884    Good
3  2034           104  Burger Singh   34233     Bad

<B> Updating data

In [13]:
# .loc[row_index,"coloumn"] = ""value

data = {
    "Year": [2021,2022,2023,2034],
    "Resturant": ["China Bowl","Subway","Dominoz","Burger Singh"],
    "Sales": [500000,21000,88884,34233],
    "Overall": ["Good","Good","Good","Bad"]
}


df = pd.DataFrame(data)


df.loc[1,"Resturant"] = "Italic Taste"

print(df)


df["Year"] = df["Year"]-1

print(df)

   Year     Resturant   Sales Overall
0  2021    China Bowl  500000    Good
1  2022  Italic Taste   21000    Good
2  2023       Dominoz   88884    Good
3  2034  Burger Singh   34233     Bad
   Year     Resturant   Sales Overall
0  2020    China Bowl  500000    Good
1  2021  Italic Taste   21000    Good
2  2022       Dominoz   88884    Good
3  2033  Burger Singh   34233     Bad

<b> Removing Columns

In [14]:
data = {
    "Year": [2021,2022,2023,2034],
    "Resturant": ["China Bowl","Subway","Dominoz","Burger Singh"],
    "Sales": [500000,21000,88884,34233],
    "Overall": ["Good","Good","Good","Bad"],
    "City": ["banglore","mumbai","nanital","uttrakhand"]
}


df = pd.DataFrame(data)

#Syntax : df.drop(columns = ["ColumnName"], inplace=True)

print(df)

df.drop(columns =["City"],inplace = True)

print(df)


#RemoviNG Multiple Coloumns 


df.drop(columns = ["Overall","Sales"],inplace=True)


print(df)

   Year     Resturant   Sales Overall        City
0  2021    China Bowl  500000    Good    banglore
1  2022        Subway   21000    Good      mumbai
2  2023       Dominoz   88884    Good     nanital
3  2034  Burger Singh   34233     Bad  uttrakhand
   Year     Resturant   Sales Overall
0  2021    China Bowl  500000    Good
1  2022        Subway   21000    Good
2  2023       Dominoz   88884    Good
3  2034  Burger Singh   34233     Bad
   Year     Resturant
0  2021    China Bowl
1  2022        Subway
2  2023       Dominoz
3  2034  Burger Singh

<B> Handling Missing Data


<b>NaN (Not a number)

None(for object data types)


isnull()

True - NaN is missing

False - value is present

In [15]:
data = {
    "Year": [2021,2022,2023,2034],
    "Resturant": ["China Bowl","Subway","Dominoz","Burger Singh"],
    "Sales": [500000,21000,88884,34233],
    "Overall": ["Good","Good","Good","Bad"],
    "City": ["banglore",None,"nanital","uttrakhand"]
}


df = pd.DataFrame(data)

print(df.isnull())

#To know how many values are missing in each coloumn 

print(df.isnull().sum())

    Year  Resturant  Sales  Overall   City
0  False      False  False    False  False
1  False      False  False    False   True
2  False      False  False    False  False
3  False      False  False    False  False
Year         0
Resturant    0
Sales        0
Overall      0
City         1
dtype: int64

<b> Handling Data

In [16]:
#Remove missing values uuse : dropna()

data = {
    "Year": [2021,2022,2023,2034],
    "Resturant": ["China Bowl","Subway","Dominoz","Burger Singh"],
    "Sales": [500000,21000,88884,34233],
    "Overall": ["Good","Good","Good","Bad"],
    "City": ["banglore",None,"nanital","uttrakhand"]
} 

df = pd.DataFrame(data)

df.dropna(axis=1,inplace=True)

print(df)

#city coloumn removed 



#axis:0 = rows
#axis =1 : coloumns 

#Default values : axis-0

   Year     Resturant   Sales Overall
0  2021    China Bowl  500000    Good
1  2022        Subway   21000    Good
2  2023       Dominoz   88884    Good
3  2034  Burger Singh   34233     Bad

<b> IF detected fill values

In [17]:
# fill values by default by using : fillna()



data = {
    "Year": [2021,2022,2023,2034],
    "Resturant": [None,"Subway","Dominoz","Burger Singh"],
    "Sales": [500000,21000,88884,34233],
    "Overall": ["Good","Good","Good","Bad"],
    "City": ["banglore",None,"nanital","uttrakhand"]
} 

df = pd.DataFrame(data)


df.fillna("Lucknow",inplace = True)

print(df)

   Year     Resturant   Sales Overall        City
0  2021       Lucknow  500000    Good    banglore
1  2022        Subway   21000    Good     Lucknow
2  2023       Dominoz   88884    Good     nanital
3  2034  Burger Singh   34233     Bad  uttrakhand

<b> Interpolation in pandas

# Interpolation in Pandas

Interpolation means filling missing values (`NaN`) by guessing values from nearby data.

Instead of putting random values like `0` or `"Unknown"`, pandas tries to estimate the missing value intelligently.

Example:

100 → NaN → 300

After interpolation:

100 → 200 → 300

Mostly used in:
- Time-Series Data
- Weather Data
- Sales Data
- Sensor Data

Pandas Function:

```python
df.interpolate()

In [18]:
data = {
    "Year": [2021,2022,2023,2034],
    "Resturant": ["China Bowl","Subway","Dominoz","Burger Singh"],
    "Sales": [500000,21000,None,34233],
    "Overall": ["Good","Good","Good","Bad"],
    "City": ["banglore","Mumbai","nanital","uttrakhand"]
} 

df = pd.DataFrame(data)

# df["Sales"]=df["Sales"].interpolate(method = "linear",axis=0)
df.interpolate(method="linear",axis=0,inplace=True)

print(df)

   Year     Resturant     Sales Overall        City
0  2021    China Bowl  500000.0    Good    banglore
1  2022        Subway   21000.0    Good      Mumbai
2  2023       Dominoz   27616.5    Good     nanital
3  2034  Burger Singh   34233.0     Bad  uttrakhand

C:\Users\shobh\AppData\Local\Temp\ipykernel_16228\226172836.py:12: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear",axis=0,inplace=True)


# Common Interpolation Methods 📈

| Method              | Meaning                        |
| ------------------- | ------------------------------ |
| `"linear"`          | straight-line estimation       |
| `"polynomial"`      | curved mathematical estimation |
| `"time"`            | based on timestamps/time gaps  |
| `"nearest"`         | use nearest value              |
| `"spline"`          | smooth curve interpolation     |
| `"pad"` / `"ffill"` | forward fill                   |
| `"bfill"`           | backward fill                  |

---

# 1. Linear (Most Common) ✅

```python id="m1v8qp"
df.interpolate(method="linear")
```

Simple straight-line estimation.

Example:

```text id="w3u6ko"
100 → NaN → 300
```

becomes:

```text id="r9p4zc"
100 → 200 → 300
```

---

# 2. Polynomial 📈

Used when data follows curves instead of straight lines.

```python id="d5n1xt"
df.interpolate(method="polynomial", order=2)
```

More advanced statistical estimation.

Mostly used in:

* scientific data
* graphs
* signals

---

# 3. Time ⏰

Used for time-series datasets.

```python id="h2z9qk"
df.interpolate(method="time")
```

Works using timestamps/dates.

Very useful for:

* stock prices
* weather data
* sensor logs

---

# 4. Forward Fill (`ffill`) 🔥

```python id="n8y0tr"
df.fillna(method="ffill")
```

Copies previous value downward.

Example:

```text id="5x2cvu"
100
NaN
300
```

becomes:

```text id="4v7pda"
100
100
300
```

---

# 5. Backward Fill (`bfill`) 🚀

Uses next value upward.

```text id="0j4lmn"
100
NaN
300
```

becomes:

```text id="c8k1fx"
100
300
300
```

---

# Important Reality 🧠

In real industry:

* `linear`
* `ffill`
* `bfill`

are most commonly used.

Advanced methods:

* polynomial
* spline

are more specialized.

<mark><b> Sorting and Aggregation

<b>Parameter	Meaning

ascending=True	       smallest → largest

ascending=False         largest → smallest</b>

In [19]:
data = {
    "Student_Name": ["Rahul", "Priya", "Aman", "Sneha", "Arjun", "Kavya"],
    "Class": [10, 10, 9, 8, 9, 10],
    "Maths": [85, 92, 76, 88, 95, 81],
    "Science": [78, 89, 80, 91, 97, 84],
    "English": [90, 85, 72, 87, 93, 79],
    "Attendance": [92, 95, 88, 90, 98, 85],
    "Sports_Score": [75, 60, 82, 70, 91, 65],
    "Result": ["Pass", "Pass", "Pass", "Pass", "Pass", "Pass"]
}

df = pd.DataFrame(data)

# #Sorting DATA in 1 Coloumn 


# # | Option            | Meaning     | Example     |
# # | ----------------- | ----------- | ----------- |
# # | ascending=True  | Small → Big | 1,2,3,4,5 |
# # | ascending=False | Big → Small | 5,4,3,2,1 |





# df.sort_values(by="Attendance",ascending = False ,inplace=True)

# print(df)




#Sorting DATA in Multiple Coloumn 


df.sort_values(["Attendance","Sports_Score"],ascending=[False,True],inplace=True)

print(df)

  Student_Name  Class  Maths  Science  English  Attendance  Sports_Score  \
4        Arjun      9     95       97       93          98            91
1        Priya     10     92       89       85          95            60
0        Rahul     10     85       78       90          92            75
3        Sneha      8     88       91       87          90            70
2         Aman      9     76       80       72          88            82
5        Kavya     10     81       84       79          85            65

  Result
4   Pass
1   Pass
0   Pass
3   Pass
2   Pass
5   Pass

<b> Aggregate in Pandas

In [20]:
data = {
    "Student_Name": ["Rahul", "Priya", "Aman", "Sneha", "Arjun", "Kavya"],
    "Class": [10, 10, 9, 8, 9, 10],
    "Maths": [85, 92, 76, 88, 95, 81],
    "Science": [78, 89, 80, 91, 97, 84],
    "English": [90, 85, 72, 87, 93, 79],
    "Attendance": [92, 95, 88, 90, 98, 85],
    "Sports_Score": [75, 60, 82, 70, 91, 65],
    "Result": ["Pass", "Pass", "Pass", "Pass", "Pass", "Pass"]
}

df = pd.DataFrame(data)


avg_attend = df["Attendance"].mean()

print(avg_attend)

91.33333333333333

<b> Grouping In Pandas

In [21]:
data = {
    "Student_Name": ["Rahul", "Priya", "Aman", "Sneha", "Arjun", "Kavya"],
    "Class": [10, 10, 9, 8, 9, 10],
    "Maths": [85, 92, 76, 88, 95, 81],
    "Science": [78, 89, 80, 91, 97, 84],
    "English": [90, 85, 72, 87, 93, 79],
    "Attendance": [92, 95, 88, 90, 98, 85],
    "Sports_Score": [75, 60, 82, 70, 91, 65],
    "Result": ["Pass", "Pass", "Pass", "Pass", "Pass", "Pass"]
}

df = pd.DataFrame(data)

print(df)

grp = df.groupby("Class")["Attendance"].count()

print(grp)

  Student_Name  Class  Maths  Science  English  Attendance  Sports_Score  \
0        Rahul     10     85       78       90          92            75
1        Priya     10     92       89       85          95            60
2         Aman      9     76       80       72          88            82
3        Sneha      8     88       91       87          90            70
4        Arjun      9     95       97       93          98            91
5        Kavya     10     81       84       79          85            65

  Result
0   Pass
1   Pass
2   Pass
3   Pass
4   Pass
5   Pass
Class
8     1
9     2
10    3
Name: Attendance, dtype: int64

<b> Grouping In Pandas with Multiple Coloumns

In [22]:
data = {
    "Student_Name": ["Rahul", "Priya", "Aman", "Sneha", "Arjun", "Kavya"],
    "Class": [10, 10, 9, 8, 9, 10],
    "Maths": [85, 92, 76, 88, 95, 81],
    "Science": [78, 89, 80, 91, 97, 84],
    "English": [90, 85, 72, 87, 93, 79],
    "Attendance": [92, 95, 88, 90, 98, 85],
    "Sports_Score": [75, 60, 82, 70, 91, 65],
    "Result": ["Pass", "Pass", "Pass", "Pass", "Pass", "Pass"]
}

df = pd.DataFrame(data)


group = df.groupby(["Class","Sports_Score"])["Attendance"].mean()

print(group)

Class  Sports_Score
8      70              90.0
9      82              88.0
       91              98.0
10     60              95.0
       65              85.0
       75              92.0
Name: Attendance, dtype: float64

## Basic Aggregation Operations :

1- sum()

2- mean()

3- count()

4- min()

5- max()

6- std()

<b> Merging and Joining Data

In [23]:
# ================================
# MERGING DATAFRAMES IN PANDAS
# ===============================

# --------------------------------
# FIRST DATAFRAME
# --------------------------------

student_data = {
    "Student_ID": [1, 2, 3, 4],
    "Name": ["Rahul", "Priya", "Aman", "Sneha"],
    "Class": [10, 10, 9, 8]
}

df1 = pd.DataFrame(student_data)


# --------------------------------
# SECOND DATAFRAME
# --------------------------------

marks_data = {
    "Student_ID": [1, 2, 3, 5],
    "Maths": [85, 92, 76, 88],
    "Science": [78, 89, 80, 91]
}

df2 = pd.DataFrame(marks_data)



# # ==========================================
# # 1. INNER MERGE
# # ==========================================

# # Keeps ONLY matching rows from BOTH tables

# inner_merge = pd.merge(df1, df2, on="Student_ID", how="inner")

# print("INNER MERGE\n")
# print(inner_merge)



# ==========================================
# 2. LEFT MERGE
# ==========================================

# Keeps ALL rows from LEFT dataframe (df1)

# left_merge = pd.merge(df1, df2, on="Student_ID", how="left")

# print("\n--------------------\n")

# print("LEFT MERGE\n")
# print(left_merge)



# # ==========================================
# # 3. RIGHT MERGE
# # ==========================================

# # Keeps ALL rows from RIGHT dataframe (df2)

# right_merge = pd.merge(df1, df2, on="Student_ID", how="right")

# print("\n--------------------\n")

# print("RIGHT MERGE\n")
# print(right_merge)



# # ==========================================
# # 4. OUTER MERGE
# # ==========================================

# # Keeps EVERYTHING from BOTH tables

# outer_merge = pd.merge(df1, df2, on="Student_ID", how="outer")

# print("\n--------------------\n")

# print("OUTER MERGE\n")
# print(outer_merge)



# # ==========================================
# # 5. CROSS MERGE
# # ==========================================

# # Creates ALL possible combinations
# # No common column required

cross_merge = pd.merge(df1, df2, how="cross")

print("\n--------------------\n")

print("CROSS MERGE\n")
print(cross_merge)

--------------------

CROSS MERGE

    Student_ID_x   Name  Class  Student_ID_y  Maths  Science
0              1  Rahul     10             1     85       78
1              1  Rahul     10             2     92       89
2              1  Rahul     10             3     76       80
3              1  Rahul     10             5     88       91
4              2  Priya     10             1     85       78
5              2  Priya     10             2     92       89
6              2  Priya     10             3     76       80
7              2  Priya     10             5     88       91
8              3   Aman      9             1     85       78
9              3   Aman      9             2     92       89
10             3   Aman      9             3     76       80
11             3   Aman      9             5     88       91
12             4  Sneha      8             1     85       78
13             4  Sneha      8             2     92       89
14             4  Sneha      8             3     76       80
15             4  Sneha      8             5     88       91

# Merging DataFrames in Pandas

## Easy Notes 🧠

| Merge Type | Meaning |
|---|---|
| `inner` | only matching rows |
| `left` | all left table rows |
| `right` | all right table rows |
| `outer` | everything from both |
| `cross` | all combinations |


# Easy Memory Trick 🔥

```text
inner  → common only
left   → save left
right  → save right
outer  → save all
cross  → multiply everything

<b><u> Concatnating Data Frames</u>

#axis = 0 -----> ROW-WISE

#axis = 1 -----> COLOUMN-WISE

# </mark>Concatenation in Pandas<mark>

Concatenation means combining DataFrames together.

---

# Types of Concatenation

## 1. Vertical Concatenation (Row-wise)

Adds rows one below another.

```python
pd.concat([df1, df2], axis=0, ignore_index=True)
````

### Notes:

* `[df1, df2]` → DataFrames to combine
* `axis=0` → combine vertically (default)
* `ignore_index=True` → resets row indexes

---

## 2. Horizontal Concatenation (Column-wise)

Adds columns side-by-side.

```python
pd.concat([df1, df2], axis=1)
```

### Notes:

* `axis=1` → combine horizontally

---

# Easy Memory Trick 🧠

```text
axis = 0 → vertical ↓
axis = 1 → horizontal →
```

```
```

In [24]:
#Combining vertically 


df_Region1 = pd.DataFrame({
    'CustomerID': [1,2],
    'Name': ['Gopal', 'Raju']})

df_Region2= pd.DataFrame({
    'CustomerID': [3,4],
    'Name':['Shyam', 'Baburao']})


print(df_Region1)


print(df_Region2)

# '''axis=0  ↓
# Rows go downward


# axis=1  →
# Columns go sideways'''
print("\n \n \n")

combined = pd.concat([df_Region1,df_Region2],axis=0,ignore_index=True)

print(combined)

print("\n \n \n")
combined2 = pd.concat([df_Region1,df_Region2],axis=1,ignore_index=True)

print(combined2)

   CustomerID   Name
0           1  Gopal
1           2   Raju
   CustomerID     Name
0           3    Shyam
1           4  Baburao




   CustomerID     Name
0           1    Gopal
1           2     Raju
2           3    Shyam
3           4  Baburao




   0      1  2        3
0  1  Gopal  3    Shyam
1  2   Raju  4  Baburao

<b> Find Duplicated Row

In [25]:
df.duplicated()

#to remove values 

df.drop_duplicates()

,Student_Name,Class,Maths,Science,English,Attendance,Sports_Score,Result
0,Rahul,10,85,78,90,92,75,Pass
1,Priya,10,92,89,85,95,60,Pass
2,Aman,9,76,80,72,88,82,Pass
3,Sneha,8,88,91,87,90,70,Pass
4,Arjun,9,95,97,93,98,91,Pass
5,Kavya,10,81,84,79,85,65,Pass

<b> Change Datatypes

In [26]:
# .astype()

<b> Countvalues of a coloumns

In [27]:
#count_values()

<b><mark> End