Business Understanding
        ↓
Data Collection
        ↓
Dataset Understanding
        ↓
Data Cleaning
        ↓
Handle Missing Values
        ↓
Handle Outliers (if required)
        ↓
Exploratory Data Analysis (EDA)
        ↓
Feature Engineering (if required)
        ↓
Encoding (if categorical data)
        ↓
Define Features (X) and Target (y)
        ↓
Train-Validation-Test Split
        ↓
Feature Scaling (Normalization / Standardization)
        ↓
Convert to Tensors
        ↓
Create Dataset & DataLoader
        ↓
Design Neural Network Architecture
        ↓
Choose Loss Function
        ↓
Choose Optimizer
        ↓
Training Loop
        ↓
Validation
        ↓
Hyperparameter Tuning
        ↓
Model Evaluation
        ↓
Save Trained Model
        ↓
Inference / Prediction
        ↓
Deployment
        ↓
GitHub + README

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
data = pd.read_csv(r"C:\Users\shobh\OneDrive\Attachments\Documents\Desktop\py\credit_card_frauds.csv")

df = pd.DataFrame(data)

In [3]:
df

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:44,"Heller, Gutmann and Zieme",grocery_pos,107.23,Orient,WA,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,49.159047,-118.186462,0
1,2019-01-01 00:00:51,Lind-Buckridge,entertainment,220.11,Malad City,ID,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,43.150704,-112.154481,0
2,2019-01-01 00:07:27,Kiehn Inc,grocery_pos,96.29,Grenada,CA,41.6125,-122.5258,589,Systems analyst,1945-12-21,413636e759663f264aae1819a4d4f231,41.657520,-122.230347,0
3,2019-01-01 00:09:03,Beier-Hyatt,shopping_pos,7.77,High Rolls Mountain Park,NM,32.9396,-105.8189,899,Naval architect,1967-08-30,8a6293af5ed278dea14448ded2685fea,32.863258,-106.520205,0
4,2019-01-01 00:21:32,Bruen-Yost,misc_pos,6.85,Freedom,WY,43.0172,-111.0292,471,"Education officer, museum",1967-08-02,f3c43d336e92a44fc2fb67058d5949e3,43.753735,-111.454923,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339602,2020-12-31 23:57:56,Schmidt-Larkin,home,12.68,Wales,AK,64.7556,-165.6723,145,"Administrator, education",1939-11-09,a8310343c189e4a5b6316050d2d6b014,65.623593,-165.186033,0
339603,2020-12-31 23:58:04,"Pouros, Walker and Spence",kids_pets,13.02,Greenview,CA,41.5403,-122.9366,308,Call centre manager,1958-09-20,bd7071fd5c9510a5594ee196368ac80e,41.973127,-123.553032,0
339604,2020-12-31 23:59:07,Reilly and Sons,health_fitness,43.77,Luray,MO,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,39.946837,-91.333331,0
339605,2020-12-31 23:59:15,Rau-Robel,kids_pets,86.88,Burbank,WA,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,46.658340,-119.715054,0
339606,2020-12-31 23:59:24,Breitenberg LLC,travel,7.99,Mesa,ID,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,44.470525,-117.080888,0

## <span style="color:#DC2626; font-family:Georgia;">Target Variable :</span>

- **<span style="color:#16A34A;">0</span>** → **<span style="color:#2563EB;">Legitimate Transaction</span>**
- **<span style="color:#DC2626;">1</span>** → **<span style="color:#EA580C;">Fraudulent Transaction</span>**

In [4]:
#data understandings


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339607 entries, 0 to 339606
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  339607 non-null  object
 1   merchant               339607 non-null  object
 2   category               339607 non-null  object
 3   amt                    339607 non-null  float64
 4   city                   339607 non-null  object
 5   state                  339607 non-null  object
 6   lat                    339607 non-null  float64
 7   long                   339607 non-null  float64
 8   city_pop               339607 non-null  int64
 9   job                    339607 non-null  object
 10  dob                    339607 non-null  object
 11  trans_num              339607 non-null  object
 12  merch_lat              339607 non-null  float64
 13  merch_long             339607 non-null  float64
 14  is_fraud               339607 non-null  int64
dtypes: float64(5), int64(2), object(8)
memory usage: 38.9+ MB

In [5]:
df.isnull().sum()

trans_date_trans_time    0
merchant                 0
category                 0
amt                      0
city                     0
state                    0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

</span>**<span style="color:#2563EB;">No null values found</span>**

In [6]:
df.duplicated().sum()

np.int64(0)

</span>**<span style="color:#2563EB;">No duplicated rows found</span>**

In [7]:
df.nunique()

trans_date_trans_time    338504
merchant                    693
category                     14
amt                       32112
city                        176
state                        13
lat                         183
long                        183
city_pop                    174
job                         163
dob                         187
trans_num                339607
merch_lat                335608
merch_long               337263
is_fraud                      2
dtype: int64

In [8]:
df.sample()

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud
224246,2020-05-26 00:26:45,Trantow PLC,grocery_net,60.48,Meridian,ID,43.6498,-116.4306,84106,Intelligence analyst,1971-02-11,8cac289912322ea19e9b38aa72c51362,43.89383,-115.70429,0

In [9]:
df.columns

Index(['trans_date_trans_time', 'merchant', 'category', 'amt', 'city', 'state',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'merch_lat',
       'merch_long', 'is_fraud'],
      dtype='object')

In [10]:
#data cleaning


df.drop(['trans_date_trans_time','dob','trans_num'],axis = 1,inplace=True)

In [11]:

df_cleaned = df.copy()

df_cleaned.to_csv(
    r"C:\Users\shobh\Downloads\AI and DATA SCIENCE\𝗗𝗲𝗲𝗽 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀\𝗗𝗲𝗲𝗽 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀 (𝗧𝗮𝗯𝘂𝗹𝗮𝗿 𝗗𝗮𝘁𝗮)\Credit Card Fraud Detection\data\credit_card_frauds_cleaned.csv",
    index=False
)

#skiping eda for you claude 


make sevral observation write it in observations markdowan cell and use various html and .md syntax to make it colourful and good and also save all graphs here 

"C:\Users\shobh\Downloads\AI and DATA SCIENCE\𝗗𝗲𝗲𝗽 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀\𝗗𝗲𝗲𝗽 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀 (𝗧𝗮𝗯𝘂𝗹𝗮𝗿 𝗗𝗮𝘁𝗮)\Credit Card Fraud Detection\images"


and write observation and all colourful in box with professionalism

In [12]:
df.sample()

,merchant,category,amt,city,state,lat,long,city_pop,job,merch_lat,merch_long,is_fraud
97179,"Robel, Cummerata and Prosacco",gas_transport,53.52,Huntington Beach,CA,33.6773,-118.0051,190249,"Therapist, horticultural",33.625295,-117.852452,0

In [13]:
#feature engineering 


X = df.drop(columns = ['is_fraud'])

y = df['is_fraud']

In [14]:
df

,merchant,category,amt,city,state,lat,long,city_pop,job,merch_lat,merch_long,is_fraud
0,"Heller, Gutmann and Zieme",grocery_pos,107.23,Orient,WA,48.8878,-118.2105,149,Special educational needs teacher,49.159047,-118.186462,0
1,Lind-Buckridge,entertainment,220.11,Malad City,ID,42.1808,-112.2620,4154,Nature conservation officer,43.150704,-112.154481,0
2,Kiehn Inc,grocery_pos,96.29,Grenada,CA,41.6125,-122.5258,589,Systems analyst,41.657520,-122.230347,0
3,Beier-Hyatt,shopping_pos,7.77,High Rolls Mountain Park,NM,32.9396,-105.8189,899,Naval architect,32.863258,-106.520205,0
4,Bruen-Yost,misc_pos,6.85,Freedom,WY,43.0172,-111.0292,471,"Education officer, museum",43.753735,-111.454923,0
...,...,...,...,...,...,...,...,...,...,...,...,...
339602,Schmidt-Larkin,home,12.68,Wales,AK,64.7556,-165.6723,145,"Administrator, education",65.623593,-165.186033,0
339603,"Pouros, Walker and Spence",kids_pets,13.02,Greenview,CA,41.5403,-122.9366,308,Call centre manager,41.973127,-123.553032,0
339604,Reilly and Sons,health_fitness,43.77,Luray,MO,40.4931,-91.8912,519,Town planner,39.946837,-91.333331,0
339605,Rau-Robel,kids_pets,86.88,Burbank,WA,46.1966,-118.9017,3684,Musician,46.658340,-119.715054,0
339606,Breitenberg LLC,travel,7.99,Mesa,ID,44.6255,-116.4493,129,Cartographer,44.470525,-117.080888,0

In [17]:
#now scaling 

from sklearn.preprocessing import StandardScaler 



numeric_columns = df.select_dtypes(include=['number'])

df[numeric_columns]

ValueError: Boolean array expected for the condition, not float64

In [16]:
df

,merchant,category,amt,city,state,lat,long,city_pop,job,merch_lat,merch_long,is_fraud
0,"Heller, Gutmann and Zieme",grocery_pos,107.23,Orient,WA,48.8878,-118.2105,149,Special educational needs teacher,49.159047,-118.186462,0
1,Lind-Buckridge,entertainment,220.11,Malad City,ID,42.1808,-112.2620,4154,Nature conservation officer,43.150704,-112.154481,0
2,Kiehn Inc,grocery_pos,96.29,Grenada,CA,41.6125,-122.5258,589,Systems analyst,41.657520,-122.230347,0
3,Beier-Hyatt,shopping_pos,7.77,High Rolls Mountain Park,NM,32.9396,-105.8189,899,Naval architect,32.863258,-106.520205,0
4,Bruen-Yost,misc_pos,6.85,Freedom,WY,43.0172,-111.0292,471,"Education officer, museum",43.753735,-111.454923,0
...,...,...,...,...,...,...,...,...,...,...,...,...
339602,Schmidt-Larkin,home,12.68,Wales,AK,64.7556,-165.6723,145,"Administrator, education",65.623593,-165.186033,0
339603,"Pouros, Walker and Spence",kids_pets,13.02,Greenview,CA,41.5403,-122.9366,308,Call centre manager,41.973127,-123.553032,0
339604,Reilly and Sons,health_fitness,43.77,Luray,MO,40.4931,-91.8912,519,Town planner,39.946837,-91.333331,0
339605,Rau-Robel,kids_pets,86.88,Burbank,WA,46.1966,-118.9017,3684,Musician,46.658340,-119.715054,0
339606,Breitenberg LLC,travel,7.99,Mesa,ID,44.6255,-116.4493,129,Cartographer,44.470525,-117.080888,0